version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_php
    volumes:
      - ./backend:/var/www
      - ./init.sh:/init.sh
      - ./setup.sh:/setup.sh
    working_dir: /var/www
    depends_on:
      - mysql
    command: ["sh", "/init.sh"]
    networks:
      - laravel_network
    expose:
      - "9000"

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel_network

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  mysql_data:
